"""initial_tables

Revision ID: a963dbd665c3
Revises: None
Create Date: 2026-09-21 19:15:00.795578

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'a963dbd665c3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
